version: '3.4'
service:
  db:
  comand: mysql --default-authentication-plugin=mysql_native_password
  restart: always
    build:
      context:
      dockerfile: Dockerfile
    environment: 
     TZ: America/Sao_Paulo
     MYSQL_ROOT_PASSWORD: Admin357/
     MYSQL_USER: root
     MYSQL_PASSWORD: Admin357/
     MYSQL_DATABASE: blog_pessoal

    network:
      - generation-network
  
  blogpessoal-api:
    network:
      - generation-network    

  networks:
     generation-network:
       drive: bridge
